-- Create Users Table
CREATE TABLE Users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    username TEXT NOT NULL,
    displayName TEXT, 
    createdAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletedAt DATE
);

-- Create Regions Table 
CREATE TABLE Regions (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    parentID INTEGER,
    createdAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletedAt DATE
    FOREIGN KEY (parentID) REFERENCES Regions(ID)
);

-- Create Boulders Table 
CREATE TABLE Boulders (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    authorID INTEGER NOT NULL, 
    name TEXT NOT NULL,
    description TEXT, 
    image TEXT, 
    grade INTEGER NOT NULL,
    coordinates TEXT,
    createdAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletedAt DATE
    FOREIGN KEY (authorID) REFERENCES Users(ID)
);

-- Create Sends Table
CREATE TABLE Sends (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    boulderID INTEGER NOT NULL,
    userID INTEGER NOT NULL,
    rating REAL,
    sendType INTEGER NOT NULL,
    createdAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletedAt DATE,
    FOREIGN KEY (boulderID) REFERENCES Boulders(ID),
    FOREIGN KEY (userID) REFERENCES Users(ID)
);